apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: docker.io/markusthoemmes/basic-500716b931f14b4a09df1ec4b4c5550d@sha256:06a71c34b05cd9d74fb9aa904ba256b525a7c39df0708b8cbbfcce923ad8af01

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: test
  name: test
spec:
  containers:
  - name: test
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10
