apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-milli
  name: liveness-milli-exec
spec:
  containers:
  - name: liveness-milli
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 500
      periodSeconds: 1500
      timeoutSeconds: 2300
      readSecondsAs: milliseconds
