apiVersion: v1
kind: Pod
metadata:
  name: basic-pod-test
spec:
  containers:
  - name: test
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - echo "hello world!"; sleep 600; exit 0
