apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 1; touch /tmp/healthy; sleep 360; rm -rf /tmp/healthy
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      periodSeconds: 1 
      periodMilliseconds: -500
      initialDelaySeconds: 0
      failureThreshold: 30
