apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 1; touch /tmp/healthy; sleep 5
#    - sleep 1; touch /tmp/healthy; sleep 60; rm -rf /tmp/healthy
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      periodSeconds: 1 
      initialDelaySeconds: 1
      failureThreshold: 30
